### PR TITLE
Added french translation file

### PR DESCRIPTION
**Pull request by elishaking**
For CRAB-28830

### CODE REVIEW

**Review by bmartinelle — APPROVED** [review]
looks good to me!

**Review by jrust — APPROVED** [review]

**Comment by jrust** [comment]
Do we have a native French speaker that can review these in the context of how they are used?

**Comment by moses-v51** [comment]
I chatted with King about modifying the code in such a way that we can store the resources in JSON files like to do for other tools.  This will better enable us to have the strings translated by Smartling, then go through the internal review process.

The juration localization requirements will also have to be spelled out in [How to request translations](https://seeq.atlassian.net/wiki/spaces/SQ/pages/2018443287/How+to+request+translations).

**Comment by moses-v51** [comment]
After further discussion with King and Michelle, we're going to have these translations reviewed by an in house native French speaker, then Internationalize this tool more fully or replace it at a later date (https://seeq.atlassian.net/browse/CRAB-28901).  I'll comment here when the translations are approved.

**Comment by moses-v51** [comment]
FYI - Our in house French reviewer is out of the office.  Michelle and I are enlisting the help of an alternate that has limited availability.  I'll update here as soon as possible.

**Comment by moses-v51** [comment]
These strings were reviewed by Nathalie Princet.  She would like the following edits:

- line 11 minute:  'm(?!s)'  -> 'm' - unless we ever display 'm' alone, if so, please remove it as an option here and replace it with 'min' below.
- line 12 remove 'hre'
- line 63 short: 'ann' --> 'an'

**Review by moses-v51 — APPROVED** [review]
French translations are approved by Nathalie Princet.

**Pull request merged**
